### ISSUE TITLE
Test to-do item

### ISSUE THREAD

**Issue by decaluwe** [coresresearch/coresresearch#2]
Testing out a first issue.

- [x] I don't know quite what I'm doing.
- [x] But I want to learn features.
- [x] So I'm trying stuff.

**Comment by decaluwe** [comment]
Is this really going to work, though?

**Comment by decaluwe** [comment]
I don't know.
